# Generated by cpp11: do not edit by hand

vl_distribution <- function(days, infecteds, r_observed_vl, population, tested_population, r_pars) {
  .Call(`_viralload_vl_distribution`, days, infecteds, r_observed_vl, population, tested_population, r_pars)
}
