# Generated by cpp11: do not edit by hand

vl_calculate <- function(day, r_infecteds, r_cum_infecteds, observed, population, tested_population, r_pars) {
  .Call(`_viralload_vl_calculate`, day, r_infecteds, r_cum_infecteds, observed, population, tested_population, r_pars)
}

vl_distribution <- function(days, infecteds, r_observed_vl, population, tested_population, r_pars) {
  .Call(`_viralload_vl_distribution`, days, infecteds, r_observed_vl, population, tested_population, r_pars)
}
